[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/bluele/slack"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/skratchdot/open-golang"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.19.1"
